# Generated by Django 4.2.6 on 2023-10-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='количество уроков'),
        ),
    ]
