# Generated by Django 4.2.6 on 2023-10-30 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_alter_lesson_course_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('date',), 'verbose_name': 'платеж', 'verbose_name_plural': 'платежи'},
        ),
    ]
