# Generated by Django 4.2.6 on 2023-11-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0008_alter_subscription_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="is_confirmed",
            field=models.BooleanField(
                default=False, verbose_name="подтверждение оплаты"
            ),
        ),
    ]
