# Generated by Django 4.2.6 on 2023-11-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0009_payment_is_confirmed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_choice",
            field=models.CharField(
                blank=True,
                choices=[
                    ("наличные", "Наличные"),
                    ("перевод на счет", "Перевод на счет"),
                ],
                max_length=50,
                null=True,
                verbose_name="способ оплаты",
            ),
        ),
    ]
